name: Proposer une règle de jeu
description: Soumettre un nouveau jeu (1 PDF + 1 image) à ajouter à LudusRegula
title: "[Nouveau jeu] "
labels: ["nouvelle-règle"]
body:
  - type: markdown
    attributes:
      value: |
        **Astuce :** le champ *Add a title* en haut de la page est le **titre de l’issue** (ex. : *Les Colons de Catane*).
        L’**Identifiant (kebab-case)** ci-dessous peut être laissé vide : une **suggestion automatique** sera postée en commentaire après envoi, à partir du *Nom du jeu*.

  - type: input
    id: name
    attributes:
      label: Nom du jeu
      placeholder: "Les Colons de Catane"
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: Identifiant (kebab-case)
      description: "Ex : les-colons-de-catane. Vous pouvez laisser vide : une suggestion sera proposée automatiquement."
      placeholder: "les-colons-de-catane"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Résumé court
      placeholder: "Résumé en 1–2 lignes…"
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: Tags (choix multiples)
      description: "Choisissez les catégories qui décrivent le mieux le jeu."
      multiple: true
      options:
        - famille
        - stratégie
        - cartes
        - coopération
        - ambiance
        - expert
        - 2-joueurs
        - party
        - deck-building
        - placement-ouvriers
        - pose-de-tuiles
        - commerce
        - bluff
        - rapide
        - enfants

  - type: checkboxes
    id: files
    attributes:
      label: Fichiers à joindre à l’issue
      description: "Merci de joindre **exactement** 1 image (vignette) **et** 1 PDF des règles en pièces jointes de l’issue."
      options:
        - label: "J’ai joint **1 image** (webp/jpg/png, ≤ 200 KB, ratio ~3:2)."
          required: true
        - label: "J’ai joint **1 PDF** (≤ 20 MB) et je détiens les droits/licences pour le partager."
          required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Crédits / Source
      placeholder: "Lien éditeur, version, remarques…"